# Generated by Django 6.1 on 2026-08-27 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=100, unique=True)),
                ('candidate_description', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(default='PENDING_REVIEW', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=150, unique=True)),
                ('standardized_description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='PENDING_APPROVAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('normalized_description', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.cpse')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='materials.materialgroup')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_score', models.FloatField()),
                ('attribute_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('critical_mismatch', models.BooleanField(default=False)),
                ('classification', models.CharField(max_length=50)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='materials.material')),
                ('material_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('MODIFY', 'Modify')], max_length=20)),
                ('reviewer', models.CharField(max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='materials.materialgroup')),
                ('national_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='materials.nationalmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='NationalMaterialMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_mappings', to='materials.material')),
                ('national_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpse_mappings', to='materials.nationalmaterial')),
            ],
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('cpse', 'material_code'), name='unique_cpse_material_code'),
        ),
        migrations.AddConstraint(
            model_name='materialgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'material'), name='unique_group_material'),
        ),
        migrations.AddConstraint(
            model_name='nationalmaterialmapping',
            constraint=models.UniqueConstraint(fields=('national_material', 'material'), name='unique_national_material_mapping'),
        ),
    ]
